purescript-emacs/psc-ide-emacs

psc-ide-protocol.el, psc-ide.el
It might be nicer to include the `read-json-from-string` into `unwrap-result`. But for now this lets the plugin work with master again.
=> unwraps the new success/error format

psc-ide.el
The displaying of the type signature happens in company-psc-ide-frontend
=> remove meta case for company

psc-ide-backported.el, psc-ide.el
There are many byte-compile warnings by not loading cl-lib.el(cl.el).
```
In company-psc-ide-backend:
psc-ide.el:75:23:Warning: misplaced interactive spec: `(interactive
(company-begin-backend (quote company-psc-ide-backend)))'
In end of data:
psc-ide.el:189:1:Warning: the following functions are not known to be defined: case, prefix,
candidates, sorted, annotation, post-command
In psc-ide-ident-pos-at-point:
psc-ide-backported.el:23:35:Warning: reference to free variable `end'
psc-ide-backported.el:33:20:Warning: reference to free variable `start'
psc-ide-backported.el:40:31:Warning: assignment to free variable `end'
psc-ide-backported.el:50:17:Warning: assignment to free variable `start'
In end of data:
psc-ide-backported.el:55:1:Warning: the following functions are not known to be …
```
=> Load cl-lib.el for using its macros

psc-ide.el
This allows me to enter "stack exec -- psc-ide-server"  for the psc-ide-server-executable variable.  As it is now I get an error when I tried to change those to use the stack commands described in the psc-ide README.
=> Allow psc-ide-server to be started using stack.

psc-ide-protocol.el, psc-ide.el, test/psc-ide-test.el
This should fix issued #7 and #10 
The imports are parsed on the init function when company is initialized and that is used later to create a module filter for the psc-ide command.
I added some test cases but some more manual testing probably wouldn't hurt. 
The one thing I couldn't figure out is how to show the completions without the qualifier prepended. For example, if I typed H.f then the completions would show "H.fob, H.foo, etc" instead of just "fob, foo".  Otherwise when the completion is expanded the qualifier would get replaced. 
Please test it out and let me know what you think.
=> Context aware completions

psc-ide.el
Because we currently filter according to the imports in the current
module, we don't get any completions for identifiers defined in the
current module, because a module doesn't import itself.
This fixes this issue while also using the new psc-ide-get-module-name
function to make a proper guess on which module to load with the load
command.
@bsermons could you review?
=> fixes completions for the current module

psc-ide-protocol.el, psc-ide.el
two new commands inside psc-ide
also makes complete matcher optional (for upcoming PR)
=> adds casesplitting and addclause

README.org, psc-ide-protocol.el, psc-ide.el
Adds rebuild commands for psc-ide, also adds fields for the upcoming rebuild cache functionality which just get ignored by older psc-ide versions.
Also removes the `C-SPC` keybinding as I find that too intrusive to emacs users.
=> Rebuild commands

psc-ide.el
Just putting this out there. This still needs a little work on windows, but I'm quite happy with how it turned out. 
This gets rid of the `psc-ide-client` usage, and instead opens network connections from inside emacs. This means we get asynchronous commands. I also implemented a blocking synchronous version becasue especially for the file modifying commands we want sequential semantics.
I also removed the response filtering and instead moved that logic into the queries we send to psc-ide. I removed filtering on explicit imports, because with the `add-import` command it's likely the user wants to see not explicitly imported identifiers for modules that he has already imported.
I'd like the adventurous @bsermons and @bodil to give this a try and see if they spot any new bugs, before we …
=> Async network

README.org
Using the existing instructions gave me the following error:
```
wrong type argument: listp, psc-ide-rebuild-on-save
```
=> Fix instructions for rebuilding on save

psc-ide.el
This simply makes for a better UX. It's become mechanical for me to load all modules after starting the server.
=> send a load all command after starting the server

README.org
This was necessary for me in order to prevent emacs-help popups. @kRITZCREEK suggested I open a pull request.
=> Added indention to emacs config

psc-ide.el, test/psc-ide-test.el
Supports import statements like 
- `import X (A) as Y`,
- `import X hiding (f)`
- and `import Y hiding (f) as Y`.
ref: https://github.com/purescript/purescript/releases/tag/v0.9.1
=> Fix import regex

psc-ide.el
* Adds a function to get the currently installed server version
Fix #68
=> Only pass globs to servers >= 0.9.2

psc-ide.el
* save the buffer before rebuild - so that all changes are taken into
account
* display all errors/warnings, instead of the first one - especially
with warnings, this is very useful as you don't have to rebuild all
the time but get a nice list
* prefix warnings/errors with "Warning" or "Error" to specify what the
message is
* when there are no more errors/warnings, don't close the window, but
only kill the buffer. The window might have been there before with
something else.
=> Improvements to the rebuild command

psc-ide.el
With Emacs 25 activating `global-eldoc-mode` by default it would be nice if we support it aswell. When `eldoc-mode` is activated, we now show the type of the identifier under the cursor automatically.
=> Eldoc support

psc-ide.el
@j0ni may I suggest this implementation for the version check instead? I'm not too familiar with the constructs you used in your implementation and it seemed like `comp` was a global variable?
=> fixes a bug with the psc-ide version check #74

psc-ide.el
Once the next version of the PS compiler is out (> 0.9.3) `psc-ide` returns types that preserve type aliases for the completion and type queries.
This PR makes it so that we can still access the expanded type signatures through `C-u C-c C-t`
Ofc we shouldn't merge this before the next PureScript release.
=> adds expanded type query

psc-ide.el
This prevents the company backend from infecting other modes and it ensures that `psc-ide-init` is only run inside of `purescript-mode` buffers, thereby avoiding inaccurate eldoc error messages in buffers using different modes (eg. without this change I'd see "eldoc-error: It seems like the server is not running"-type errors in my `*scratch*` buffer).
=> avoid activating company backend outside of purescript-mode

psc-ide.el
This can be used to specify the output directory for psc-ide-server, which is
necessary for some custom project setups. Fixes #81
=> adds a new customization variable psc-ide-output-directory

psc-ide.el, test/psc-ide-test.el
Eldoc can be very annoying when the server has a hickup or the project got large enough that a type command is noticeable lag during typing.
I removed the test because in order to keep it working I'd have to break the show-type command into lots of smaller functions and I didn't want to do that since the type command doesn't contain any actual logic but the formatting and that's straightforward enough for my taste.
=> Query type information asynchronous

psc-ide.el
The function `string-to-int` is obsolete and unavailable in development versions of emacs.
See https://www.gnu.org/software/emacs/manual/html_node/elisp/String-Conversion.html
=> Use string-to-number instead of obsolete string-to-int

README.org, psc-ide.el
[psc-ide](https://github.com/kRITZCREEK/psc-ide) is deprecated.
#95
=> replace `psc-ide-server` with `purs ide server`

CHANGELOG.md, psc-ide-protocol.el, psc-ide.el, test/psc-ide-test.el
A GIF speaks a thousand words:
This also stops the completion from adding imports. The behaviour can be toggled with the `psc-ide-add-qualification-on-completion` variable.
This PR also contains two small unrelated changes, where one is the addition of the `list import` command for purs ide, and the other one is to display the results of the loading command.
=> Shows the qualifier for completions, if they've already been imported qualified

psc-ide-protocol.el, psc-ide.el
Only works with the current PS master, but as soon as a new release is cut this'll work. When invoking the add import command on a qualified identifier, we now suggest modules to import under that qualifier.
=> add qualified imports

CHANGELOG.md, psc-ide-protocol.el
Larger responses get sent in chunks, and so we need to call `accept-process-output` multiple times, until the process is actually finished.
=> Collects multiple process output chunks in send-sync

psc-ide-protocol.el
we're not using these yet, since they aren't really backwards compatible
=> adds functions to send completion options

CHANGELOG.md, psc-ide-flycheck.el, psc-ide-protocol.el, psc-ide.el
Adds the necessary flags and parameters for `--editor-mode`, which will be in the next compiler release.
It's turned off by default, in order to not break existing setups. I haven't added any documentation yet, but I intend to give the README a major rewriting anyway, so I figured I'd group that work.
I've tested this, but I invite anyone to try this with the current PureScript master. The main benefit is that we don't rely on watching the output directory anymore. This means more reliable reloads on Linux, and less idle CPU usage on Windows (because of no polling). It also means source locations get refreshed whenever a file succesfully gets rebuilt.
=> Editor mode

psc-ide-backported.el, psc-ide.el
This attempts to fix my commit that broke operator imports identified in #132 
The `psc-ide-build-type-command` function was also removing the leading dot for operators like `.>`, which seems to be fixed here so hopefully I didn't break anything with that change.
=> Better handling for identifiers with dot's

psc-ide.el
gets rid of the leftover garbage buffer from running psc-package sources
=> kill current buffer and window from psc-package sources

psc-ide.el
unfortunately, kill-buffer-and-window will end up killing windows* even if the
results buffer is created and used, and it seems to conditionally create a
second window to take a hold of.
=> delete the windows of the results buffer then kill it

psc-ide.el
I tried setting up a project with psc-package, and found some issues with psc-ide-emacs' recently-added support (thanks!) for detecting psc-package source globs. Here are some little fixes:
- Use call-process instead of shell-command, so that Emacs' exec-path is used (this allows Emacs packages like `add-node-modules-path` to find `psc-package` if it was installed via `npm`)
- Don't split the glob list on spaces, which would break when directory paths contain spaces
- When psc-package.json exists and psc-package can't be executed successfully, raise an error instead of failing silently
- Reformat docstring to satisfy checkdoc
=> More robust code for extracting psc-package sources

CHANGELOG.md, psc-ide-flycheck.el, psc-ide-protocol.el, psc-ide.el
There are various workflows that don't start the ide server from within Emacs, so I'd like to support those too. For example:
- A coworker starts his ide server from an NPM script
- I know people share an ide instance with a running `pscid` process
- Myself hacking on the ide server
I've wanted to do this for a long time, so thank you @purcell (if you could take a look at this change that would be great!) for finally getting me to do it :D I've just got one request, please add a short note to `CHANGELOG.md` if you make a change that changes the plugins behaviour in a visible way.
=> Smarter server offline detection

README.org, psc-ide-protocol.el, psc-ide.el
Add custom codegen options to "rebuilds" and default to ["js"].
Think the code is right but I haven't figured out the workflow of testing it in a project.
I'm trying to use purerl backend but I get the error:
The foreign module implementation for module X is missing.
=> Rebuild codegen

psc-ide.el
this freezes emacs for no good reason, while load-all correctly is async to allow the user to keep doing things while waiting for the response. goes from typical freezing of 3 - 10 seconds to async update
=> load module should not be sync

psc-ide.el
with direnv and other tools like such, you can just set env vars per project for what you actually want to work with.
in my case, i either do not use a purescript package manager or i use psc-package. when i do not use a purescript package manager, i have the packages provided in other ways such that i know where my dependencies are and can set them to PURS_IDE_SOURCES.
=> allow setting source globs with PURS_IDE_SOURCES

psc-ide.el
Dash 2.18.0 now subsumes `dash-functional`.
See https://github.com/magnars/dash.el/blob/master/NEWS.md#from-217-to-218
=> Replace deprecated dash-functional dependency

CHANGELOG.md, psc-ide.el
Also adds detection for new `spago.yaml` project file
Fixes #200 
Unfortunately I just can't make this work on Windows, and I've given up on trying.
EDIT: Okay, I learned about inheritenv and Emacs's stupid behaviour around processes and temp buffers... Now it works on Windows as well.
=> uses npx instead of the now defunct `npm bin`
