- psc-ide.el
> Support new JSON command API

- psc-ide.el
We need to follow normal Lisp guidelines at least with parens. It is not C, we don't need to place each paren on the new line.
Also sorted the code around the correct sections.
> Bring code back to lisp guidelines.

- README.org
> Add keybindings to the README

- psc-ide-protocol.el
- psc-ide.el
Implemented filters and matchers
> Implemented psc-ide-protocol

- psc-ide-protocol.el
Just a little fix to comply with the protocol
> fix keys in filter

- psc-ide.el
> Ask projectile-root for project dir (re #3)

- .gitignore
- Cask
- psc-ide.el
Some clean up changes to prepare the package for the MELPA submission
> MELPA submission preparation

- psc-ide-backported.el
- psc-ide-protocol.el
- psc-ide.el
Fixes for the MELPA submission review https://github.com/milkypostman/melpa/pull/3215
> MELPA submission review

- psc-ide.el
This fixes an issue I was having when trying to query the type info for a qualified identifier since it would look for 'T.foo' instead of just 'foo'.  This will also add a filter for the appropriate modules.
> Show type info for qualified identifiers.

- psc-ide.el
This should be applied on top of #38
> Properly flex match

- psc-ide-protocol.el
- psc-ide.el
> Remove company frontend

- psc-ide-protocol.el
- psc-ide.el
> Switch to new executable

- README.org
- psc-ide.el
Also fixes a bug @doppioslash ran into, where `~` wouldn't be resolved to the home directory.
> Nicer errors

- README.org
- psc-ide-flycheck.el
- psc-ide-protocol.el
- psc-ide.el
New PR with some improvements from @marsam
> Flycheck support

- psc-ide-flycheck.el
> Fix warnings shown as errors.

- psc-ide.el
> Fix module search regex

- psc-ide-flycheck.el
Fix for #50 
Would like this one to be tested by someone else.  Seems to work okay for me though.
> Use temp buffer

- psc-ide.el
This fixes an issue with starting the server.
> fix reference to unbound variable `compared`

- README.org
- psc-ide.el
Works for me, but I'm fairly new to elisp, so please suggest changes if this is not optimal. Fixes #79.
> Add psc-ide-use-npm-bin option

- psc-ide-flycheck.el
- psc-ide.el
fixes #86 
@bsermons does this look about right?
> Add missing dependencies for flycheck integration

- psc-ide.el
Reference implementation for https://github.com/purescript/purescript/pull/2946
> adds Prim completion (works for PS versions > 0.11.5)

- psc-ide-backported.el
> Show help when cursor is over dot

- psc-ide.el
This is mostly so I can easily send the `--polling` flag on windows since I didn't see another way to do it.
> Allow extra args to server

- psc-ide-flycheck.el
> Fix key binding in flycheck code.

- psc-ide-protocol.el
- psc-ide.el
use variable psc-ide-host instead of string literal "localhost"
> add variable psc-ide-host

- psc-ide-protocol.el
- psc-ide.el
!! DO NOT MERGE THIS YET !!
This is a PoC implementation, it needs a compiler release first. As per usual I have a GIF:
> Implements an xref backend for the new find-usages functionality

- CHANGELOG.md
- README.org
- psc-ide.el
from https://github.com/epost/psc-ide-emacs/issues/141
> add starting psc-ide-server with psc-package sources run in root

- psc-ide.el
fixes not being able to work with multipart qualified import names
> handle qualified import names the same way as import names

- psc-ide.el
As an adjunct to #157, I've gone through and tidied up a bunch of little inconsistencies I found, including some lurking bugs. :-)
> Misc fixes

- CHANGELOG.md
- README.org
- psc-ide.el
> Spago support

- psc-ide.el
Fixes #185
@dariooddenino Want to give this a try?
> Uses the npm local spago binary if psc-ide-npm-use-bin is set
